import type { OpenSourcePackageDto } from '../../core/domain/open-source-license.dto';

export const OPEN_SOURCE_PACKAGES: OpenSourcePackageDto[] = [
  {
    name: 'Creators Desk (Core)',
    version: '0.1.0',
    license: 'MIT',
    description: '창작자를 위한 미니멀 마크다운 지식 저작 환경 및 에디터',
    repositoryUrl: 'https://github.com/Sunggu/creators-desk',
    commercialUseAllowed: true,
  },
  {
    name: 'React & React-DOM',
    version: '^19.2.8',
    license: 'MIT',
    description: '사용자 인터페이스 구축을 위한 선언형 컴포넌트 라이브러리',
    repositoryUrl: 'https://github.com/facebook/react',
    commercialUseAllowed: true,
  },
  {
    name: 'CodeMirror 6',
    version: '^6.11.1',
    license: 'MIT',
    description: '웹 브라우저를 위한 확장 가능하고 경량화된 고성능 코드/텍스트 에디터',
    repositoryUrl: 'https://github.com/codemirror/dev',
    commercialUseAllowed: true,
  },
  {
    name: 'Tailwind CSS v4',
    version: '^4.3.3',
    license: 'MIT',
    description: '유틸리티 우선 CSS 프레임워크',
    repositoryUrl: 'https://github.com/tailwindlabs/tailwindcss',
    commercialUseAllowed: true,
  },
  {
    name: 'Hono & Hono Node Server',
    version: '^4.13.12',
    license: 'MIT',
    description: '웹 표준 기반의 초고속 Universal 경량 웹 프레임워크',
    repositoryUrl: 'https://github.com/honojs/hono',
    commercialUseAllowed: true,
  },
  {
    name: 'Marked',
    version: '^18.0.14',
    license: 'MIT',
    description: '속도와 표준 준수에 최적화된 마크다운 컴파일러',
    repositoryUrl: 'https://github.com/markedjs/marked',
    commercialUseAllowed: true,
  },
  {
    name: 'Vite',
    version: '^8.3.0',
    license: 'MIT',
    description: '차세대 프론트엔드 빌드 툴 및 번들러',
    repositoryUrl: 'https://github.com/vitejs/vite',
    commercialUseAllowed: true,
  },
  {
    name: 'TypeScript',
    version: '~6.0.2',
    license: 'Apache-2.0',
    description: '정적 타입을 지원하는 자바스크립트 상위 집합 언어',
    repositoryUrl: 'https://github.com/microsoft/TypeScript',
    commercialUseAllowed: true,
  },
];
